### ISSUE TITLE
Add average queue wait time

### ISSUE THREAD

**Issue by matthardcastle-affirm** [buildkite/buildkite-agent-metrics#106]
I alert on spikes in running and scheduled jobs. Sometimes these spikes cause long wait times but they usually don't. What I would like to monitor is the average wait time for jobs in a queue.

Is this a feature you would consider adding?

**Comment by jayco** [comment]
Hey @matthardcastle-affirm, Thanks for the suggestion!

We had a bit of a discussion about this and it doesn't seem like something that's appropriate to add here as all elastic stacks hammer that constantly to know how much work there is to do.

That said, this metric is something worth capturing and long term this is the sort of reporting we absolutely do want to provide nicely, internally. It would be great if you could capture this as a feature request here https://forum.buildkite.community/c/feature-requests/11 so we could open it up for further discussion in the community.

**Comment by matthardcastle-affirm** [comment]
Thank you for looking into this @jayco.
