### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by mogggggg** [buildkite/buildkite-agent-metrics#110]
Hi,
Can we please get a binary published with ARM support?

**Comment by sj26** [comment]
Sure thing! I've just pushed commits so that new releases will be built with golang 1.16, added linux-arm64 and darwin-arm64 as cross compile targets. I've also updated the latest stable release with arm64 binaries:
https://github.com/buildkite/buildkite-agent-metrics/releases/tag/v5.2.0

**Comment by mogggggg** [comment]
@sj26 That was so quick... you are an absolute legend!
