### ISSUE TITLE
Support for provided.al2 runtime

### ISSUE THREAD

**Issue by p33rs** [buildkite/buildkite-agent-metrics#202]
AWS is deprecating the `go1.x` runtime in favor of `provided.al2`. More details here: https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/

I am attempting to update my deployment to work with the new runtime.

Wish I could pitch in on this, but I'm not familiar with the go build process.

# Implementation

According to the link above, we need to update the Lambda to ...
- run on `provided.al2` runtime
- change the handler name to `bootstrap`
- Add `-tags lambda.norpc` to the build [optional]

# Attempted Fix

I've attempted simply renaming the file from the `5.7.0` release `handler.zip` to `bootstrap` and reuploading my Lambda with the new runtime and handler.

This results in the following error:
`/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /var/task/bootstrap)`

**Comment by moskyb** [comment]
hey mate! we have work for this (and similar work for our other headliner go lambda, [buildkite-agent-scaler](https://github.com/buildkite/buildkite-agent-scaler)) prioritised, and will have updated lambdas available prior to EOL for the go1.x runtime.

in the meantime, i think you might be able to fix your particular issue by compiling the lambda with `CGO_ENABLED=0` - we'll push an update making this change soon.

**Comment by p33rs** [comment]
That's great, thanks! I'll keep an eye out for it.
