### ISSUE TITLE
Support cluster-unique queue names

### ISSUE THREAD

**Issue by lucylura** [buildkite/buildkite-agent-metrics#224]
# Description
The buildkite-agent-metrics binary does not support Buildkite Clusters.
Queue names in clusters can be cluster-unique, and if there is 2 or more queues with the same name across multiple clusters, their metrics will be combined.
This causes issues with autoscaling.

# Solution
Add support for cluster-unique queue names.

# Ideas
Add a`Cluster` dimension to metrics.

**Comment by NotArpit** [comment]
@DrJosh9000 @triarius pinging you both as you've reviewed my PRs previously :) Are there any plans to namespace metrics based on Buildkite cluster so we can drive AutoScaling more granularly?

**Comment by DrJosh9000** [comment]
Hi @NotArpit @lucylura, I'll be looking into this. We definitely want the clusters experience to be good 👍

**Comment by lucylura** [comment]
hey @DrJosh9000 @triarius what's the ETA on getting Clusters support? We are feeling the pain of this now and it's blocking our adoption of Clusters

**Comment by DrJosh9000** [comment]
Hi @lucylura, thanks for the poke. We'll get a release with #227 out soon!
