### ISSUE TITLE
publish new versions go package manager

### ISSUE THREAD

**Issue by kyuhyunc** [buildkite/buildkite-agent-metrics#247]
on [this page](https://pkg.go.dev/github.com/buildkite/buildkite-agent-metrics?tab=versions), I last publish was done in 2018.
Could you publish newer versions to the go artifactory?

**Comment by DrJosh9000** [comment]
Thanks for the report @kyuhyunc!
v5.9.3 (currently being released) is now visible on pkg.go.dev: https://pkg.go.dev/github.com/buildkite/buildkite-agent-metrics/v5
