### ISSUE TITLE
Support for builds inside teams

### ISSUE THREAD

**Issue by pvdvreede** [buildkite/buildkite-agent-metrics#4]
Do this support gathering metrics from projects inside a team? Eg a Project that is not in the everybody team?

**Comment by pvdvreede** [comment]
I think it might, but there is no way to filter by a team.

**Comment by toolmantim** [comment]
Alas the API endpoint this uses doesn't support any team-based filtering. When it does, this sounds like it makes sense. I'm curious though, why not just report all pipeline metrics?

**Comment by lox** [comment]
It's been a while since we've heard anything back, so closing this one for now.
