### ISSUE TITLE
Unclear whether to run singleton or one per agent?

### ISSUE THREAD

**Issue by petemounce** [buildkite/buildkite-agent-metrics#41]
I read the readme, and haven't concluded whether there's just supposed to be a single active instance of this at any given point, or whether there should be one per agent...? It _sounds_ like the former?

We use prometheus for metrics & alerting. So, given that, if I run this on every agent but just scrape one of them, that _ought_ to be a reasonable thing to do...?

**Comment by toolmantim** [comment]
Ah, sorry for the confusion. It's designed to designed to be run as a singleton, on a single machine that can send to prometheus. Running it on every agent might push your API token over the requests-per-minute limit, and then your metrics would stop working.

Sounds like you're not wanting to have it running standalone somewhere though? Could you share a little more about that?

**Comment by petemounce** [comment]
Singleton; ok.

I think I had vaguely assumed that this process would be somehow listening to the agent(s) on the host, or that it was a plugin to the agent, and that it would report metrics by eavesdropping. 

It hadn't occurred to me that it would be polling your service (and therefore be subject to rate limiting) until I read the command line usage.

That's made me wonder how to find information about your rate limiting. Do you give quota information back as response headers, like github do? Is there an endpoint I can hit to ask for current rate limit remaining? I haven't noticed this covered in your docs so far, but it has been mentioned in passing in conversations with support.

**Comment by petemounce** [comment]
I had been planning to scrape every five seconds; I'll probably want to reconsider my life choices.

Finally; the cli and install experience here isn't consistent with your agent. Any reason? Accepting PRs, if it's not a priority? I've never made a deb before, might have a go...

**Comment by lox** [comment]
Apologies @petemounce, the primary usecase for `buildkite-metrics` has been as part of the AWS Elastic Stack, so we've tended to not document it's standalone usage well. We need to remedy that! I'll see what I can do.

**Comment by petemounce** [comment]
Ah, no worries. I've stood it up inside of our kubernetes with only a little trouble.

That trouble was around supplying the token secret to it - for a reason I don't understand, the kubernetes deployment configuration didn't expand the environment variable when it was used within the deployment's `args` element. I worked around it by creating a docker container that has a wrapper script in it that expects the environment variable.

It would be generally convenient to be able to supply `-token_path` as an alternative to `-token`, and have the tool read the file there (trimming whitespace off each end) on the basis that it'll be a single line containing the secret. That also avoids the secret being inside the environment, which I've been told is reasonably easy to sniff (but my linux clue is really not adequate to knowing the ins and outs of that).

**Comment by lox** [comment]
>which I've been told is reasonably easy to sniff (but my linux clue is really not adequate to knowing the ins and outs of that).

For what it's worth, generally when folks say that they are talking about horribly old linux's, on modern operating systems the security guarantees of reading a processes env are the same as accessing a file. You need to be root, or the process. The security risk associated with secrets in ENV are all around concerns that they might be easier to accidentally disclose either to error logging tools or to subprocesses (which get the env of the parent). 

There is a comprehensive trace through of process env in modern linux here: https://security.stackexchange.com/questions/14000/environment-variable-accessibility-in-linux/14009#14009

**Comment by petemounce** [comment]
Thanks for the link, I'll read up.

Can you think of something possible to set up that is less manual toil than a trusted contributor doing a code review of a contribution, per commit, before allowing a build to happen from an external contributor...? So far, that's the best I've come up with :(

**Comment by lox** [comment]
In general @petemounce, or relating to the running of a buildkite-metrics daemon?

**Comment by petemounce** [comment]
Sorry; I meant in general. I've emailed you privately what I'm concerned about.

**Comment by lox** [comment]
I've clarified this in the README, let us know if it's still not clear.
