### ISSUE TITLE
MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by lanox** [buildkite/buildkite-agent-metrics#44]
Hi, 

I have provided token from agent page, however I get ```MissingRegion: could not find region configuration``` when running it locally from my laptop. I can also confirm in my .aws/config regions is set.

```
2018/07/09 13:16:34 Collecting agent metrics for all queues
2018/07/09 13:16:35 Buildkite > BusyAgentCount = 0
2018/07/09 13:16:35 Buildkite > TotalAgentCount = 4
2018/07/09 13:16:35 Buildkite > ScheduledJobsCount = 0
2018/07/09 13:16:35 Buildkite > RunningJobsCount = 0
2018/07/09 13:16:35 Buildkite > UnfinishedJobsCount = 0
2018/07/09 13:16:35 Buildkite > IdleAgentCount = 4
2018/07/09 13:16:35 Buildkite > [queue = default] > TotalAgentCount = 4
2018/07/09 13:16:35 Buildkite > [queue = default] > IdleAgentCount = 4
2018/07/09 13:16:35 Buildkite > [queue = default] > BusyAgentCount = 0
2018/07/09 13:16:35 Extracted 9 cloudwatch metrics from results
2018/07/09 13:16:35 Submitting chunk of 9 metrics to Cloudwatch
MissingRegion: could not find region configuration
```

**Comment by lanox** [comment]
by exporting export AWS_REGION= seem to fix the problem above. Can this be added to README ?or mentioned somewhere.

**Comment by lox** [comment]
Hi @lanox, sorry about that! The aws sdks doesn't read from `.aws/config`, that's generally just for the aws cli tools. Perhaps this needs to be provided as a required arg value so the error is clearer?

**Comment by lpuljic** [comment]
@lox  I think it makes sense to have that as arg.
