### ISSUE TITLE
Development process instrumentation

### ISSUE THREAD

**Issue by patsplat** [buildkite/buildkite-agent-metrics#47]
Hello,

Thanks for putting this library together!

The README.md states that this is primarily concerned with instrumenting agent status for auto scaling.  However we're looking to add metrics related to dev process and in particular the Github integration:

- Buildkite > (Queue) > (Branch) > CurrentStatus
- Buildkite > (Queue) > (Branch) > LinesAdded
- Buildkite > (Queue) > (Branch) > LinesRemoved
- Buildkite > (Queue) > OpenPullRequests
- Buildkite > (Queue) > PullRequestMaxAge
- etc

If the above were implemented would this be a good home for dev process metrics?

Cheers,

Patrick

**Comment by lox** [comment]
Hi @patsplat! Currently `buildkite-metrics` is mostly about consuming metrics from the Buildkite API and sending them to Cloudwatch/Prometheus/Statsd. We don't currently track any of those metrics or expose them via our API's, so I'm not sure it would be a good fit.

How are you planning on collecting those metrics and where are you planning on publishing them?

**Comment by patsplat** [comment]
Hi @lox !

Could add an SCM option to publish the metrics via statsd to Datadog.  Happy to build the feature.

Rolling our own felt excessive considering the pleasantly tight binding between Buildkite and SCM provider.  Most of the criteria seems generic.

**Comment by lox** [comment]
Sounds interesting! So are you imagining you'd directly query Github's API for the above data?

**Comment by patsplat** [comment]
Anything I should know before I jump into building this?

**Comment by lox** [comment]
Given we've moved this repo to metrics specific to the agent, I'm going to close this one out.
