### ISSUE TITLE
Published docker image?

### ISSUE THREAD

**Issue by yob** [buildkite/buildkite-agent-metrics#51]
I'm interested in experimenting with this on a GKE cluster, mainly to see if I can easily export the metrics via prometheus and link it to a horizontal pod autoscaling setup.

I could build my own docker image, but I'm a pretty lazy person. Is there are chance we could get an official image published to docker hub (`buildkite/agent-metrics` or similar?). The `buildkite/agent` image has been perfect for use in GKE, and this would be a good companion image.

**Comment by lox** [comment]
Good idea!

**Comment by yob** [comment]
For anyone else who comes across this, we ended up using the [myobplatform/buildkite-metrics/](https://hub.docker.com/r/myobplatform/buildkite-metrics/) image

**Comment by amalucelli** [comment]
Hey guys, first thanks for this exporter 🚀

I followed @yob comment and opened the PR buildkite/buildkite-agent-metrics#77 with a base `Dockerfile` that can be used to create a local image. I'm using it right now over a GKE cluster without any problems.

Is there any plans to automate this to push to the official docker registry? I would suggest the [goreleaser/goreleaser](https://github.com/goreleaser/goreleaser) to automate that build and push operations.

I'm not sure how could I help, but with an official image for the metrics, we could add it as another `Deployment` to the official [`helm` chart](https://github.com/buildkite/charts), so we could even have an exporter by default.

**Comment by lox** [comment]
Thanks, I'll see if I can find some time to get this published as an official image

**Comment by CorbinSimpsonDaedalus** [comment]
Hi! My use case is basically like the one described. We are paying customers and we would feel more comfortable in our supply chain if we were to use a container image from Buildkite, our trusted vendor. Thanks for your hard work!

**Comment by tylerauerbeck** [comment]
This feels fairly long in the tooth at this point, but is there any plan to publish an image for this? From a quick look around I still don't see one that's published anywhere.

**Comment by tylerauerbeck** [comment]
@DrJosh9000 It looks like this path already exists for other `buildkite` apps like `agent`. Could we just yank something like this: https://github.com/buildkite/agent/blob/main/.buildkite/steps/publish-docker-images.sh into this repo (with the other attached script(s)/pipeline steps) and add it to the publishing pipeline?

**Comment by DrJosh9000** [comment]
Just fixing the release pipeline to make it work...

**Comment by DrJosh9000** [comment]
It's alive! https://gallery.ecr.aws/buildkite/agent-metrics
