### ISSUE TITLE
Running as an AWS Lambda instructions has broken link

### ISSUE THREAD

**Issue by paulolai** [buildkite/buildkite-agent-metrics#53]
Under "Running as an AWS Lambda" in the README it has the following insturctions:
 
"Take a look at https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/metrics.yml for examples of usage."

If you visit the link you get a 404. Where can I find a good example file?

**Comment by lox** [comment]
Sorry about that! Try https://github.com/buildkite/elastic-ci-stack-for-aws/blob/v3.3.0/templates/metrics.yml.
